# This is a basic workflow to help you get started with Actions

name: passing job values

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  pass_in_one_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set color
        id: color-selector
        run: echo "COLOR=green" >> $GITHUB_ENV

      - name: Get color
        run: ${{ steps.color-selector.outputs.COLOR }}
        
  producer:
    runs-on: ubuntu-latest
    steps:
      - name: Make a sentence
        id: sentence_maker
        run: |
          echo "message=Hello from producer job!" >> $GITHUB_ENV

  consumer:
    runs-on: ubuntu-latest
    steps:
      - name: Print the message
        run: |
          echo $message
          echo "Received: ${{ needs.producer.outputs.job_message }}"

  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > result.txt

      - name: Upload result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: result-artifact
          path: result.txt
  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: result-artifact
      - shell: bash
        run: |
          value=$(cat result.txt)
          echo "Value from artifact: $value"
          echo "Result after multiplying by 9: $((value * 9))"