name: Display Variables Example

on:
  workflow_dispatch:

env: # Zmienne w scopie workflow
  cat_name: "Puszek"
  WORKFLOW_VAR: "To jest zmienna workflow"

jobs:
  display-variables:
    name: ${{ vars.ENVIRONMENT_VAR }}
    environment: test 
    runs-on: ubuntu-latest

    env:
      JOB_VAR: "To jest zmienna joba"

    steps:
      - name: Use variables 1
        env: 
          STEP_VAR: "To jest zmienna stepu"
        run: |
          echo "Repository variable : $REPOSITORY_VAR"
          echo "Repository variable: ${{ vars.REPOSITORY_VAR }}"
          echo "Organization variable : $ORGANIZATION_VAR"
          echo "Environment variable : $ENVIRONMENT_VAR"
          echo "Ala ma kota o nazwie $cat_name"
          echo "Powinna być zmienna w scopie workflow: $WORKFLOW_VAR"
          echo "Powinna być zmienna w scopie joba: $JOB_VAR"
          echo "Powinna być zmienna w scopie stepu: $STEP_VAR"

      - name: Use variables 1
        run: |
          echo "Ala ma kota o nazwie $cat_name"
          echo "Powinna być zmienna w scopie workflow: $WORKFLOW_VAR"
          echo "Powinna być zmienna w scopie joba: $JOB_VAR"
          echo "NIE powinna być zmienna w scopie stepu: $STEP_VAR"

      - name: Show all environment variables
        run: |
          echo "ALL ENVIRONMENT VARIABLES"
          env


  display-variables2:
    name: Display Workflow-Scoped Variables
    runs-on: ubuntu-latest
    steps:
      - name: Use variables in display-variables2
        run: |
          echo "Powinna być zmienna w scopie workflow: $WORKFLOW_VAR"
          echo "NIE powinna być zmienna w scopie joba: $JOB_VAR"
          echo "NIE powinna być zmienna w scopie stepu: $STEP_VAR"

      - name: Show all environment variables
        run: |
          echo "ALL ENVIRONMENT VARIABLES"
          env
